---
- name: "APT and systemctl"
  hosts: all
  become: yes
  connection: ssh
  tasks:
    - name: "download from APT"
      ansible.builtin.apt:
        name: tuned
        state: present

    - name: "launch tuned"
      ansible.builtin.systemd_service:
        name: tuned
        enabled: yes
        state: started

    